sudo: required
language: d
d:
    - dmd
services:
    - docker
before_install:
    - sudo apt-get install -y libevent-dev
    - docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    - docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.2.0&
    - sleep 20
    - docker ps -a
    - curl http://127.0.0.1:9200/_cat/health | grep "green"
script:
    - dub run vibed-elastic-logger:test
    - curl http://127.0.0.1:9200/vibe_logger_test/_search | grep "Logger test message"
